# Jekyll configuration for FractaLedger GitHub Pages
title: FractaLedger Documentation
description: Comprehensive documentation for the FractaLedger system
url: https://aryanduntley.github.io/fractaledger
baseurl: /fractaledger

# Theme settings
# Using custom layouts instead of a theme
markdown: kramdown
highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Default layout
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"
  - scope:
      path: ""
    values:
      layout: "default"

# Navigation
navigation:
  - title: Home
    url: /
  - title: Getting Started
    url: /getting-started
  - title: API Reference
    url: /api-reference
  - title: Transceivers
    url: /transceivers
  - title: Chaincode
    url: /chaincode
  - title: Advanced Features
    url: /advanced-features
  - title: Extending
    url: /extending

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
